version: '3.8'

services:
  library-server:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
